version: '3.7'

services:

  db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    
  web:
    container_name: web
    image: alexey-fedchishyn/bushop:new
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
