# Generated by Django 5.0.1 on 2024-01-07 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='banner/')),
                ('link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Бренд', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Категорія', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tit', models.ImageField(upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\proj\\images')),
                ('stit', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\proj\\images')),
                ('static1', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\proj\\images')),
                ('static2', models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\proj\\images')),
                ('Модель', models.CharField(max_length=200)),
                ('Колір', models.CharField(max_length=200)),
                ('Ціна', models.CharField(max_length=200)),
                ('Ціна2', models.CharField(max_length=200)),
                ('Розмір', models.TextField()),
                ('Кількість', models.IntegerField()),
                ('Опис', models.TextField(blank=True, null=True)),
                ('Знижка', models.IntegerField(default=0)),
                ('Бренд', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borcivky.brand')),
                ('Категорія', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borcivky.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('second_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('warhouse', models.TextField()),
                ('pay', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('done', models.BooleanField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='borcivky.product')),
            ],
        ),
    ]
