# Generated by Django 5.0.1 on 2024-01-08 21:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
