# Generated by Django 5.0.1 on 2024-01-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0003_alter_product_static1_alter_product_static2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fourth',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='second',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='third',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='static1',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='static2',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stit',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tit',
            field=models.ImageField(upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\images'),
        ),
    ]
