# Generated by Django 5.0.1 on 2024-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0004_product_first_product_fourth_product_second_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='static1',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\static\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='static2',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\static\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stit',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\static\\images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tit',
            field=models.ImageField(upload_to='C:\\Users\\__name__\\OneDrive\\Рабочий стол\\shopborcivky\\static\\images'),
        ),
    ]
