# Generated by Django 5.0.1 on 2024-01-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0005_alter_product_static1_alter_product_static2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='banner',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
