# Generated by Django 5.0.1 on 2024-01-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0007_alter_product_first_alter_product_fourth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='first',
            field=models.TextField(),
        ),
    ]
