# Generated by Django 5.0.1 on 2024-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borcivky', '0011_alter_product_ціна_alter_product_ціна2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='static1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='static2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stit',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tit',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
